import type { Metadata } from "next";
import { fonts } from "./fonts";
import "./globals.css";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "Admin | Coffee Nerds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts.bobby.variable} ${fonts.brandon.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
